import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import '../public/assets/css/style.css'
// import  '../public/assets/css/style.css.map'
import "../layoutcomponents/layout.css";
import  NavBar from '../layoutcomponents/NavBar'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
         <body className='page-main flex'>
                <div><NavBar/></div>
                <div>{children}</div>
                  
           </body>
    </html>
  );
}
